---
- name: "Configure custom kernel repository if required"
  when: kernel_manage_custom_repo | bool
  block:
    - name: "Install custom kernel yum repo"
      yum_repository:
        name: "{{ kernel_custom_repo_name }}"
        description: "{{ kernel_custom_repo_description }}"
        baseurl: "{{ kernel_custom_repo_baseurl }}"
        gpgcheck: "{{ kernel_custom_repo_gpgcheck | default('no') }}"
        gpgkey: "{{ kernel_custom_repo_gpgkey | default(omit) }}"
        enabled: "{{ kernel_custom_repo_enabled | default('no') }}"
      register: _kernel_custom_repo

    - name: "Install custom kernel yum repo gpgkey"
      rpm_key:
        state: present
        key: "{{ kernel_custom_repo_gpgkey }}"
        fingerprint: "{{ kernel_custom_repo_gpgkey_fingerprint | default(omit) }}"
      when: kernel_custom_repo_gpgkey is defined

    - name: "Clean yum cache if repository updated"
      command: yum clean all
      args:
        warn: false
      when: _kernel_custom_repo.changed

- name: "Ensure CentOS Vault repositories list is up to date"
  package:
    name: centos-release
    state: latest  # noqa 403
  retries: 10
  delay: 1
  when: ansible_distribution == 'CentOS'

- name: "Get available kernel versions with YUM"
  command: "yum list --enablerepo=C7.* --enablerepo={{ kernel_custom_repo_name | default('custom.*',true) }}.* --showduplicates kernel"
  changed_when: false
  args:
    warn: false
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"
  register: yum_kernel_list

- name: "Set target YUM kernel version"
  set_fact: _kernel="{{ yum_kernel_list |
                     rhel_kernel(kernel_version, ansible_kernel) }}"
  when: yum_kernel_list is not skipped

- name: "Ensure kernel packages versions with YUM"
  yum:
    name: "{{ item.name }}-{{ _kernel }}"
    enablerepo: "{{ yum_kernel_list |
                 rhel_repo(kernel_version, ansible_kernel) }}.*"
    allow_downgrade: "{{ item.downgrade | default(false) }}"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"
    - item.when
  with_items:
    # Kernel and kernel-devel have multiversion support, so do not need
    # to be downgrades
    - name: kernel
      when: true
    - name: kernel-devel
      when: "{{ install_kernel_headers | bool }}"
    - name: kernel-headers
      when: "{{ install_kernel_headers | bool }}"
      downgrade: true
    - name: perf
      when: "{{ install_perf | bool }}"
      downgrade: true
    - name: python-perf
      when: "{{ install_perf | bool }}"
      downgrade: true
    - name: bpftool
      when: "{{ install_bpftool | bool }}"
      downgrade: true
